### ISSUE TITLE
Show Well-Rested status on UI

### ISSUE THREAD

**Issue by DocSchlock** [LittleLightForDestiny/littlelight#10]
When selecting a character in either Equipment or Progress, show a UI element on the header to indicate if the character still has the Well-Rested buff for the week.

**Comment by marquesinijatinha** [comment]
does this makes sense? or is too small/too hidden to notice?
![image](https://user-images.githubusercontent.com/305022/57960756-ffbb8e80-78e0-11e9-87c3-adb3a0565eb8.png)

**Comment by DocSchlock** [comment]
That's perfect. Exactly where it makes sense.

**Comment by marquesinijatinha** [comment]
added in update 1.5.93
