### ISSUE TITLE
add chrome os support

### ISSUE THREAD

**Issue by YamazakiRobert** [LittleLightForDestiny/littlelight#107]
you can't login using chrome on chrome os and have to install the chrome beta or dev to login and the icons for perks are blurry to see

**Comment by joaopmarquesini** [comment]
1) That's an issue with the default chromeOS browser and android apps in general, so I don't think there's something I can do to fix it.
2) I need to check if I'm able to reproduce this issue somehow to debug it, but unfortunately I don't have a chrome OS device. I'm going to research if there's something I can do to fix it or if that's a framework incompatibility issue and all I can do is wait.

**Comment by YamazakiRobert** [comment]
you can use brunch https://github.com/sebanc/brunch to test chrome os support
i don't know if is possible to little light to use a hook to WebView or another browser render to open the login screen inside the app 
https://developer.android.com/guide/webapps

**Comment by joaopmarquesini** [comment]
I don't think that would solve the issue, as it's chromeOS default chrome browser that won't "talk" to android apps.
An internal webview on the app will be based on the system OS and will likely have the same problem.
Also it goes against Bungie guidelines to show their login page as a part of the app (chrome custom tabs and safari controller view are ok though).
As there's already a workaround for that (by using another browser) I wouldn't consider that an issue to be fixed on LL.

**Comment by YamazakiRobert** [comment]
chrome os has a android webview, then they will not use the chrome and use the android webview instead
