### ISSUE TITLE
special perks and masterwork status

### ISSUE THREAD

**Issue by YamazakiRobert** [LittleLightForDestiny/littlelight#109]
elemental capacitor, celerity, bottomless grief and masterworks for non adept weapons status are showing all the benefits, they only need to be informational
dim has this mitigation applied

**Comment by YamazakiRobert** [comment]
https://github.com/DestinyItemManager/DIM/commit/486b95ebdb06cabec9978e3f14e4838517f5d81b
https://github.com/DestinyItemManager/DIM/commit/72bc3908b0ee7dd7b01cf14ad612299b46e7d24c

**Comment by YamazakiRobert** [comment]
this are the fixes if i´m not wrong

**Comment by TheBrenny** [comment]
Is this a dupe of #87 and #86?

**Comment by joaopmarquesini** [comment]
fixed on 1.8.0
