### ISSUE TITLE
Cannot Add Another Acc

### ISSUE THREAD

**Issue by DigitalVein222** [LittleLightForDestiny/littlelight#111]
I have tried several times to add another acc to LL.
I have tried uninstalling the app, clear cache but I still cannot add another acc.
A few weeks ago I was able to but not now.

**Comment by joaopmarquesini** [comment]
I changed some stuff on the login process lately, I'm going to check if I broke this somehow

**Comment by YamazakiRobert** [comment]
i have this problem too but copying the link o anonymous page and continuing the process i can add another account,
i noticed that when you add another account the previous one have error on login switch 
using the incognito or anonymous mode i can add another account
maybe is a cookie issue ?

**Comment by joaopmarquesini** [comment]
hmmm if that's the case sounds like a Bungie issue perhaps ?
I'm going to investigate it a bit further.

**Comment by joaopmarquesini** [comment]
hey @DigitalVein222 I made a fix for this on the latest version.
If that doesn't solve your issue, please reopen.

**Comment by DigitalVein222** [comment]
It fixed it yahoo. You are fantastic thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
