### ISSUE TITLE
Bug with equipping loadouts

### ISSUE THREAD

**Issue by TheBrenny** [LittleLightForDestiny/littlelight#118]
I think there's a bug with equipping loadouts where it ends up ignoring and/or equipping wrong items sometimes.

The reproducibility for this is hit and miss. Sometimes it works without issue, sometimes it just breaks.

I'm going to do some digging to see what I can find.

**Comment by fsmdeveloper** [comment]
did you find any solution?

**Comment by TheBrenny** [comment]
Not that I could see. I'm convinced it has something to do with a possible race condition between two+ async calls, but I couldn't find anything.

**Comment by joaopmarquesini** [comment]
closing as the loadout equipping was entirely redone.
maybe it's fixed, maybe we will have new bugs.
