### ISSUE TITLE
bungie_api -  [flutter  dart package] null safety issue

### ISSUE THREAD

**Issue by fsmdeveloper** [LittleLightForDestiny/littlelight#119]
Please update that package with null safety support

**Comment by joaopmarquesini** [comment]
hey @fsmdeveloper can you take a look at:
https://github.com/LittleLightForDestiny/bungie-api-dart/tree/null-safety
I'm not very familiar with `null-safety` migration yet, and as most of that code is automated I'm trying to move a bit slowly with this.

**Comment by joaopmarquesini** [comment]
hey @fsmdeveloper, I think I can close this one right?
latest published version is null safe enabled.
https://pub.dev/packages/bungie_api
