### ISSUE TITLE
God Roll not Showing Up

### ISSUE THREAD

**Issue by DriZeWwWwW** [LittleLightForDestiny/littlelight#121]
I have weapons on my Characters and in my Vault that are God Rolls but they aren't showing up as God Rolls on my Little Light App

**Comment by joaopmarquesini** [comment]
there are two things that can cause this:
1) Wishlists are subjective, so not everyone will agree on what's a godroll.
2) even if a weapon have all perks considered as a godroll on the app, that doesn't mean the weapon itself will be considered a godroll.
The main reason for this is the weapon considers multiple builds, so if you get godroll perks on 2 slots from one build and the other 2 from other build, so even if the weapon has godroll perks on each slot, it may not constitute a godroll
