### ISSUE TITLE
Recommended Rolls Changing Almost Hourly For Me

### ISSUE THREAD

**Issue by Evilcandy30** [LittleLightForDestiny/littlelight#122]
For some reason on my app a weapon will be listed as a god roll but an hour later if I check again it won't be. And then an hour or two after that it will be a god roll again. The weapons from the new season sometimes have good/god perk listings but sometimes those same weapons won't have the same symbols next to them at all. 

Is there anyway to fix this is seems to happen quite often for me. Any help would be greatly appreciated

**Comment by joaopmarquesini** [comment]
try to remove all wishlists and re-add them throught settings.

**Comment by joaopmarquesini** [comment]
Also, this is a known bug, I will try to fix it soon
