### ISSUE TITLE
dependency bungie api package miss

### ISSUE THREAD

**Issue by lclbm** [LittleLightForDestiny/littlelight#126]
The pubspec.yaml configuration declared in the file is as follows:
```
bungie_api: 
    path: ../bungie-api-dart
```
But the path "../bungie-api-dart" does not exist.
Then I went to download the latest bungie_api 12.10.0 at https://pub.dev/packages/bungie_api.
The program still cannot run normally, some methods and parameters are missing.
Is it the bungie-api-dart" latest version and hasn't been updated yet?

**Comment by joaopmarquesini** [comment]
Hey, sorry @lclbm , I was testing the null-safe version locally and forgot to change it back.
Check now, it's fixed.
