### ISSUE TITLE
Weapon's Rolls Changes

### ISSUE THREAD

**Issue by Flannel-Thunder** [LittleLightForDestiny/littlelight#128]
Hello,

I am messaging because I seem to be having a possible issue with my app. I had built my weapons inventory based on what this app had recommended as "good rolls" or "God rolls" by looking at either the blue icon, red icon, or a gold ringed icon. Last week, I was on the app and everything looked as it should. All my weapons I had in my inventory had the proper color codings and so forth. However, the next day, I got on Little Light, and about 90% of the weapons I had in my inventory were missing most, if not, all of the color coding it had the day before. I have checked for updates to the app as well as uninstalled and reinstalled the app, and unlinked my destiny 2 account and then reconnected it to the app, but it's not fixing this "issue." Any help, or explanation would be most welcome. Thank you so much for such a useful and easy to use app! I have enjoyed it very much! Attached is a screenshot of some of the weapons I have. All the "kinetic" weapons had at least the blue color coding, with most also having the gold ring as well.
![Screenshot_20211229-202916](https://user-images.githubusercontent.com/96851091/147714593-56195c51-e95b-4a34-a26a-69197deddcb4.png)

**Comment by TheBrenny** [comment]
Not 100% sure, but the Wishlists (aka god rolls lists) aren't actually curated _in_ Little Light, but in external JSON files. If you go to settings, and then find wishlists, you'll see that you can add various recommended lists, or even your own, as long as it conforms to the right formatting (https://wishlists.littlelight.club).

I'd say what you just encountered was that the wishlist curator updated a few weapons, considering the changing sandbox along with the newer weapons that got released.

**Comment by Flannel-Thunder** [comment]
Interesting. I had no idea that's how that worked. Thank you for your help
and the info!

**Comment by TheBrenny** [comment]
All good, happy I could help! 😁

@joaopmarquesini Suggest closing. 🎉

**Comment by joaopmarquesini** [comment]
Hey @TheBrenny thanks for answering it. My GH notifications is overflowing with IRL work stuff and I keep missing issues on LL.
@Flannel-Thunder it's pretty much what Brenny answered, with two aggravating factors that happened in season 14.
On season 14 one of the main curators stopped playing, and then 4 people stepped in to fill the void. That ended up in very inflated wishlist, where almost everything was considered at least a good roll.
Also on the beginning of the season we usually are not so certain of what's good and what not, so having more wishlists also makes sure you don't shard anything that "can be good".
When the sandbox changes dropped and we got a wishlist updated, I thought it was a good window to remove the other ones, as we already got the time to experiment and check what please and most people are entering their "spring cleaning" phase where they are sharding old weapons to make room for new ones.
But if you want to go back to the old wishlist, you can always add them back on little light through the popular wishlists menu. 
The ones that were on the main wishlist before and aren't anymore are "big-bird's", "kj45j415" and "adhere clan".

**Comment by Flannel-Thunder** [comment]
Thank you for that info. I had no idea how complex some of this stuff is.
Thanks for being the ones that maintain and understand it! Is there a
recommended wishlist I should stick to that is pretty consistent?

**Comment by joaopmarquesini** [comment]
@Flannel-Thunder tbh that changes a lot since everything depends on voluntary work.
Right now the ones that are updated with more frequency I think are `Just Another Team`, `Big Bird` and `Avowed Clan`(previously Adhere Clan).
I'm moving away from having a default wishlist and making users choose their one exactly because I don't want to push something that is purely my opinion on others.
