### ISSUE TITLE
Login workflow not working on the Android app on Chromebook

### ISSUE THREAD

**Issue by ozone** [LittleLightForDestiny/littlelight#129]
The app lets me choose the language, then it downloads the Destiny manifest, then asks me to authorize the app on my Bungie account. This open a webpage in Chrome (the native app, not an Android version) on bungie.net. At this point I approved the app from my Stadia account and my PSN account, and get returned to the login page asking me to authorize the app. I've cleared the cache and storage between attempts. I suspect the problem comes from the jump between the native browser and the Android app. This worked on other apps, like the Destiny companion app.

(Big thank you for maintaining this amazing app, and happy new year!)

**Comment by ozone** [comment]
I found a workaround by installing the Firefox Focus Android app, and by making it the default browser. The workflow works with this app. I guess the Little Light URLs aren't being redirected to the app from the native browser.

**Comment by joaopmarquesini** [comment]
Hi ozone, that's it. I'm not sure why but for some reason Chrome OS system browser won't forward the login code to LL. I'm doing a major rework on the login process right now and that "may" fix it, but I can't tell for sure as I don't have a Chromebook to test it.

**Comment by ozone** [comment]
I should be able to help with this. Happy to test it for you when you think it's ready.

**Comment by joaopmarquesini** [comment]
Hey @ozone I think I fixed it on the login flow rewrite, but forgot about the GH issue... can you test it?

**Comment by ozone** [comment]
It works perfectly! Thank you for fixing this, and apologies for taking so long to test it!
