### ISSUE TITLE
Lost the ability to tag items

### ISSUE THREAD

**Issue by robear23** [LittleLightForDestiny/littlelight#131]
Loved the tag feature. However it is no longer an option on items. Would appreciate some help with this, thanks :)

**Comment by joaopmarquesini** [comment]
Hi @robear23 I'm investigating why this stopped working for some users. It happens just on some edge cases, and I'm not sure yet what causes it. Will keep you informed once I find it.

**Comment by ianbaguskas** [comment]
Same here. I just installed for the first time on an Apple iPad and there is no option to tag items. Tried every which way. Can’t figure it out.

**Comment by TheBrenny** [comment]
I think this is coming from `notes` never getting initialised into something that's not `null`. I'm currently investigating a workaround.
