### ISSUE TITLE
Add in settings the option "Default tab when opening LL" 

### ISSUE THREAD

**Issue by XTugaX** [LittleLightForDestiny/littlelight#14]
When we open LL by default it opens in Equipment, give the possibility for the user to choose where he/she want the app to open will be a good quality improvment, maybe some people just use the app for tracking and opening by default to "Objectives" will make more sense or "Loadouts", etc.

**Comment by marquesinijatinha** [comment]
Not exactly.
The app will default to the latest tab you opened. It's just that some I don't consider relevant enough to be considered ( like duplicated items ) or doesn't have that functionality implemented yet (like objectives)

**Comment by RaSSieL86** [comment]
It seems a good idea to me. A drop-down control in which the first is "Last tab opened" and the rest each of the tabs there are.
