### ISSUE TITLE
Add a icon to the triumphs we are tracking

### ISSUE THREAD

**Issue by XTugaX** [LittleLightForDestiny/littlelight#15]
Having a icon to the triumphs we are tracking will make it easy do recognize them when we are browsing the list of all the triumphs, I made a not pretty pic with 2 exemples just to get the idea across
![Screenshot_20190419_025622](https://user-images.githubusercontent.com/49588400/56414628-d01d5600-6250-11e9-8c66-6ab3418d74b1.jpg)

**Comment by marquesinijatinha** [comment]
added in 1.5.84
