### ISSUE TITLE
Option to swipe left/right on the "Progress" section

### ISSUE THREAD

**Issue by XTugaX** [LittleLightForDestiny/littlelight#16]
Since by default on the Progress section we have Milestones and Pursuits we should be able to swipe left or right to move between them instead of have to click on the tabs on the bottom.

After implementing that option those tabs should be moved to the top since we really don't have to touch them and is taking space from a area that your one hand use can reach.

**Comment by RaSSieL86** [comment]
This change has already been implemented. When you swipe, you switch between different sections instead of between characters.

**Comment by marquesinijatinha** [comment]
thanks for that @RaSSieL86 
also, now if you swipe over the character "banner" it will switch characters
