### ISSUE TITLE
Have all the pursuits together

### ISSUE THREAD

**Issue by XTugaX** [LittleLightForDestiny/littlelight#17]
Will be nice have all the Clan / Dreamcity / Gambit / Etc Pursuits to gather, i.e., one after another, right now there is Gambit in the middle of DC, Clan ones on top and bottom
![Screenshot_20190419-084152_Little Light](https://user-images.githubusercontent.com/49588400/56426955-be06dc00-627f-11e9-8708-da7c8d50ee41.jpg)

**Comment by RaSSieL86** [comment]
It would be interesting to know what method Destiny uses to organize the bounties in the game

**Comment by marquesinijatinha** [comment]
Need to check, but yes, any kind of order is better than no order at all, which is what we have right now

**Comment by marquesinijatinha** [comment]
added in v1.6.0something
