### ISSUE TITLE
Surround Deepsight Weapons with Orange Border

### ISSUE THREAD

**Issue by TheBrenny** [LittleLightForDestiny/littlelight#172]
I like to farm the Deepsight Weapons from time to time, so being able to quickly identify them from the equipment screen would be a neat feature!

**Comment by joaopmarquesini** [comment]
Is this a WQ thing ? I wasn't able to play yet

**Comment by TheBrenny** [comment]
Yeah. Technically it's part of Free to Play, but came with WQ. Idk if the API has any references to it.

**Comment by joaopmarquesini** [comment]
it does :)
<img width="505" alt="image" src="https://user-images.githubusercontent.com/305022/156435959-79f332dd-ff4c-448a-8cec-bf749525047b.png">

I'm just looking for the progress info and will push the update as soon as I find it

**Comment by joshrosario310** [comment]
Is it possible to consider an icon of some sort in addition? I'm colorblind and struggle to differentiate the borders in-game for Masterwork vs Attunement. I've been using a custom item tag and manually tagging them as I obtain in-game but it would be cool to be able to just filter a search for these attunements directly.

**Comment by TheBrenny** [comment]
I guess it might be possible to put a shaded corner in the bottom left (similar to how god rolls have shaded corners in the top right). That way, a shaded corner means it's a DS weapon, the icon means it's shaped, and nothing is a normal weap.

Otherwise, perhaps automatically tagging DS and shaped weaps is another option.

**Comment by joshrosario310** [comment]
The changes are great, lower left was a good call and I love that I can just search for "Deepsight" to bring them all up. Is it possible to add "Attune" to the search tags as well?

**Comment by joaopmarquesini** [comment]
Oh that was an unexpected side effect, you can search for "shaped" when looking for crafted weapons

**Comment by TheBrenny** [comment]
Closing because this is implemented in af8574f2b18456c4346b2100417b1f23f6e20c1d. Swift work and done well! 🎉
