### ISSUE TITLE
Weapon Layout not working

### ISSUE THREAD

**Issue by joshrosario310** [LittleLightForDestiny/littlelight#178]
After the latest update, when there are no weapons on a character the (+) slots are not showing up and it's viewing as though Only Equipped is selected, even when choosing other Tile Size modes.

Not sure if this is by design but I liked using those empty slots to quickly grab weapons of the correct slot.

Version v1.9.1 on iOS14

![IMG_4542](https://user-images.githubusercontent.com/56232460/156621211-0f99bfa5-55e1-47f7-87d6-e62b6d4a9304.PNG)

**Comment by joaopmarquesini** [comment]
That's a side effect from another fix, I'm gonna fix it on the next release
