### ISSUE TITLE
iOS app no longer available in US App Store

### ISSUE THREAD

**Issue by spnkr** [LittleLightForDestiny/littlelight#18]
Please put it back, I really like this app! I am an iOS developer and can help with the coding or app submission process. Would love to help.

**Comment by marquesinijatinha** [comment]
Hey spnkr, thanks for the offer, but it's more a financially related problem than a development one. My dev license expired and I wasn't able to raise enough money to renew it in time. It's 60-ish % complete, so hopefully it will go back to the store soon.

**Comment by marquesinijatinha** [comment]
Hey spnkr, the app is back
https://itunes.apple.com/us/app/little-light-for-destiny-2/id1373037254?l=en&mt=8
