### ISSUE TITLE
Find duplicate items in terms of perks

### ISSUE THREAD

**Issue by ImmortalZypther** [LittleLightForDestiny/littlelight#19]
Currently, the duplicate item finder just finds duplicate items, but I think it would have even more value if it found "true" duplicates. Since armors in this game have random rolls, you can have 2 armors with the exact same set of perks even if they look different. For example: you can have a Prodigal Hood with (Shotgun Targeting, Power Weapon Targeting) + (Grenade Launcher Reserves, Machine Gun Reserves) and a Wing Theorem with the exact same set of perks.

This is just an example though, I just pulled a random set of perks from my equipment, but I've definitely seen exact duplicates of perks in my vault before. They show up in there because if the perks look good, I'll save it for later. If it shows up again, I might've forgotten about the first time and then I'll just send it to vault again.

Another feature that can ride on this one is if you can pick what perks to search duplicates for by slot. So if you don't care about the first slot (Heavy armor, Light armor, Exotic perks, etc.), you can just search for the second, third, and fourth slots. Or if you're searching for alternative perk sets in the second shot but want to keep a specific setup in the third and fourth slots.

Off the top of my head, I know of no inventory manager that can provide this feature quickly and easily without any outside tools like exporting into an excel worksheet. If you add this, I think it'd be a very welcome addition for the Destiny community.

**Comment by XTugaX** [comment]
I approve this message! 👌🏻

**Comment by marquesinijatinha** [comment]
Hmmm I like the idea but I'm not sure this fits on dupes.
maybe in search with a multiple perks filter ? (like when you type shotgun targeting in search field, but in a way it filters by more than one perk)
or do you think that having to search for it kills the purpose ?
