### ISSUE TITLE
Game Assist page

### ISSUE THREAD

**Issue by avlis** [LittleLightForDestiny/littlelight#192]
Hi all, first of all, amazing work! keep it up!

I have been using the loadouts page to assist in quick weapon and armor changes in real-time (during play), but what would be amazing would be a new page focused on assisting real-time gameplay.
With the current character selected on the top, and then a nice layout of names & icons of loadouts, for instance.

This way, we could have a fast "one-click" loadout. Imagine it on a tablet, with loads of screen space ... 

Maybe some other stuff could go there, like some kind of warnings/messages, or timers (countdown on how long until the super or grenades is charged, for instance).
But I don't know the API, so not sure that last one is possible.

Best Regards!

**Comment by TheBrenny** [comment]
On the equipment screen, you can tap the ghost at the top to show a quick actions menu where you can equip max light, random gear, equip/transfer loadouts, and even make loadouts from the gear you've got in your inventory. Is this kind of what you're looking for?

In terms of cooldown timers, that's not an API thing, so yeah, wouldn't be possible.

I know DIM has a "farming mode" feature where it automatically transfers everything out from the character's inventory, but I don't know how useful it would be, considering you can just pull lost items from the post master and manage gear that way.

Great ideas though! Real-time features are definitely handy!

**Comment by joaopmarquesini** [comment]
I've been wanting to implement a farming mode for a while now, along with an "activity planner"
Don't think real-time time info would be possible, but item suggestions depending on the current activity would be really cool.
Also I've been wanting to trash the entire milestone and turn it into something more useful
Something that is not on my plans is taking too much advantage of big screens, it's just not a Little Light thing. LL was born on phones and scaled to larger devices, and that is something I plan to stay loyal to.

**Comment by TheBrenny** [comment]
I've always wanted to have a Bounty Optimiser feature, and I guess that's considered "real time". But I don't know if it's off-topic for this issue.

**Comment by avlis** [comment]
Thanks for your response!

I hadn't found yet that shortcut menu on the ghost, its something on that direction, thanks.

but I was imagining something more... "one click", so we would not have to click multiple times to get to a loadout.

That "bounty optimiser" is also a great suggestion, so we could "re-focus" on the bounty objectives with a quick glance at the screen, instead of having to pop-up the bounty tracking screen on the game itself.

Thanks and keep up the good work!

**Comment by avlis** [comment]
About the activity planner: I have a kind of "pre-flight checklist on orbit", where I consider the bounties I purchase (Zavala / Banshee-44 / local vendors), and weapon loadout. So yes, something that would ease that task would be great as well!

**Comment by avlis** [comment]
Also, as you commented DIM: it would be nice to see the stats of armor with separated numbers/color bars for base / mod added points like they do , so it's easier to identify the origin of stats.

**Comment by joaopmarquesini** [comment]
closing for now as there's too much stuff going on on LL
