### ISSUE TITLE
Last time played is being cut

### ISSUE THREAD

**Issue by Theovorn** [LittleLightForDestiny/littlelight#197]
I noticed that this is cut with certain amounts of time while talking with Rassiel.
Happens on my phone (Realme 6 Pro) in vertical and horizontal mode, default text size and even emulated on BlueStacks.
Once translated in italian:
16 hours will fit
about one day will not fit (see the picture)
about one week will not fit <- guessing this as i cannot test it but if exists in the API will be surely longer than the previous one
Example:
![image](https://user-images.githubusercontent.com/79859852/160716842-aed18015-8c50-4791-b842-344cbdce760e.png)
Unfortunately i cant make tests as im not an API expert whatsoever.
I hope this is enough for you to understand the issue.
I am available on Discord if you need more informations.

**Comment by RaSSieL86** [comment]
Perhaps turning off overflow and allowing the box to grow up, which has vertical space, will fix it.

**Comment by joaopmarquesini** [comment]
can't reproduce on my phone, gonna check if it's still happens and if it do will fix it on 2.0.2 😅 (years after)
