### ISSUE TITLE
Default perk's availability should be checked too

### ISSUE THREAD

**Issue by kj415j45** [LittleLightForDestiny/littlelight#203]
Issue originally reported in [Discord by Swerlz](https://discord.com/channels/550698622757634089/558384070967689248/1001564856576643264)

Weapon "Tigerspite"<640114618>.socket[3] has a default value (or say `singleInitialItemHash`) which is "Kill Clip"<1015611457>. However, in its `randomizedPlugSetHash` <1765257316> there's no "Kill Clip" at all. That means "Kill Clip" will never appear on that slot.

Currently LL would not marked it as invalid perk in Collections screen, while it should be.

**Comment by joaopmarquesini** [comment]
Is that the case for all weapons ?
the contents of `singleInitialItemHash` aren't the "Bungie roll" for some weapons ?

**Comment by kj415j45** [comment]
> Is that the case for all weapons ?
> Aren't the contents of `singleInitialItemHash` the "Bungie roll" for some weapons ?

I think Bungie just use `singleInitialItemHash` for items' showcase in Collections scrren. There's an extra example, "Chattering Bone"<568515759> has a kill clip at 3rd perk slot's `singleInitialItemHash`, but it will never appear on random-roll version of this weapon. It can only drop on curated version.

However, it looks like only weapons release before Shadowkeep has the similar issue. I'm not sure about this since we have so much weapon.

**Comment by joaopmarquesini** [comment]
@kj415j45 can you confirm if this is still wrong in the current version ?

**Comment by kj415j45** [comment]
> @kj415j45 can you confirm if this is still wrong in the current version ?

@joaopmarquesini It's still wrong in `2.0.1`.
 ![Screenshot_2023-07-18-08-22-15-012_me.markezine.luzinha.jpg](https://github.com/LittleLightForDestiny/littlelight/assets/18349191/0fc8a092-2c42-48f3-bc08-f10bdc9a75df)

**Comment by kj415j45** [comment]
Btw, I can not see other perks with `currentlyCanRoll: false` being marked as not available in this view either.

**Comment by bill0042** [comment]
Also, perks on collectible items have the option to "Apply trait". Sticky grenades on Wendigo GL3 is one example with "currentlyCanRoll: false" that the previous version showed as disabled, but no longer shows that. For perks that are only in singleInitialItemHash (only roll on the curated version), I think there are so few cases of this and on such old weapons, that it doesn't matter that we show these perks as normal perks.

**Comment by joaopmarquesini** [comment]
let me see if I understand:
we shouldn't show singleInitialHash when we have randomPlugSet unless it's included on randomPlugSet
Additionally, we should disable singleInitialHash (and all other plugs) that have currentlyCanRoll:false.
Is that right ?
