### ISSUE TITLE
Recoil direction not showing.

### ISSUE THREAD

**Issue by Wickedstrife** [LittleLightForDestiny/littlelight#209]
I can't see recoil direction anymore on the app. It shows the number but not the little half circle visual. I tried re-installing but it's still blank. Love the app and appreciate you.
![Screenshot_20221204-133733_Little Light](https://user-images.githubusercontent.com/119811423/205509145-66d2ed94-8d29-493e-9ffe-dd49c11c714d.jpg)

**Comment by joaopmarquesini** [comment]
Yeah, Bungie changed the perk "id" so Little Light is using an old one.
I'm working on a big rework on the app and don't think I will be able to fix it right now, but as soon as I finish it I can fix it.

**Comment by joaopmarquesini** [comment]
already fixed on the dev release, to be published in the next weeks
