### ISSUE TITLE
Mismatch of items in the list of duplicates when updating

### ISSUE THREAD

**Issue by RaSSieL86** [LittleLightForDestiny/littlelight#21]
When the list is updated because an item was deleted, the others appear with erroneous attributes

**Comment by marquesinijatinha** [comment]
@RaSSieL86 can you confirm if this is fixed in the latest version ?

**Comment by RaSSieL86** [comment]
Confirmed, it does not happen anymore

**Comment by marquesinijatinha** [comment]
thanks, closing then
