### ISSUE TITLE
Inventory takes forever to update in the app

### ISSUE THREAD

**Issue by AlDorado9000** [LittleLightForDestiny/littlelight#211]
Since several weeks now, the inventory of my guardians takes a very long time to update to/display the actual current items. Example: I move one item to the vault (it takes a bit until the item is actually transferred) and it can take 5 - 10 minutes until the app finally stops showing it in the inventory. 
Example: I have all 9/9 helmet slots full and move 1 away, it briefly shows the slot empty but then reverts back to the item I no longer have there. Since these items are still showing in the app (app: 9/9, game: 8/9), if I move a different helmet to my guardian, it moves a random one to the vault and replaces it with the one I pulled. In-game it goes from 8/9 -> 8/9 instead of 8/9 -> 9/9 slots full. This happens on all my phones, even a fresh installation of the app did not help.

**Comment by joaopmarquesini** [comment]
Will be fixed in the next release
