### ISSUE TITLE
Wishlist display changes request - always show wishlist, group wishlist notes with wishlist

### ISSUE THREAD

**Issue by bill0042** [LittleLightForDestiny/littlelight#215]
1. Always display wishlists
One of the many great features of Little Light is the wishlists which are currently only displayed in the item details screen when a weapon is marked as having a good or god roll. I find this info to be very useful and would like to see it in all cases.
2. Move wishlist notes to immediately after the wishlist under the same section heading
The text is very large in Pandapaxxy's wishlist, would be better near the bottom, and belongs with the wishlist itself.
3. In the wishlists, make enhanced perks appear yellow or with the enhanced perk background
In wishlists with enhanced perks, the enhanced perks appear exactly the same as non-enhanced perks so they appear as duplicates. In the Destiny manifest, enhanced perks are given the same icon so it would be necessary to identify them and make them appear differently.

**Comment by joaopmarquesini** [comment]
I think most of this (if not all) is applied in the loadout_mods branch right ?

**Comment by bill0042** [comment]
> I think most of this (if not all) is applied in the loadout_mods branch right ?

Yes. Its even better than I hoped. Thanks!
