### ISSUE TITLE
 I have a problem

### ISSUE THREAD

**Issue by Imtatar** [LittleLightForDestiny/littlelight#236]
Hello.  I'm from Russia.  I have a problem.  The application asks Banshee for activation, but after activation on the site, the application again asks Banshee to activate the account.  Can this situation be resolved?

**Comment by bill0042** [comment]
The account activation works for me and I have tried several times. Also, no one else is reporting this issue. Have you tried logging into your account at bungie.net?

**Comment by Imtatar** [comment]
Yes, to your account.  Maybe I have some problem with my phone.  I will try to log into my account from another phone.  I will let you know the result.

**Comment by Imtatar** [comment]
I tested the application on another phone, the account was registered and everything worked.  now I will decide what could happen on my phone.  why the app is not working.  thanks for answering my letter.
