### ISSUE TITLE
Overview of armor elemental protection

### ISSUE THREAD

**Issue by rsdebest** [LittleLightForDestiny/littlelight#25]
Is it possible to display an overview of total elemental protection on the armor page?
Just like mobility, resilience and recovery but for void, solar and arc instead.
That would save the user a ton of time manually counting and deciding if the current loadout is right for the job.

**Comment by RaSSieL86** [comment]
Maybe add option in setting page?

**Comment by marquesinijatinha** [comment]
yep, totally possible. I currently hide those stats from details page
Also I think I broke the stats in the last update and it's showing stuff that it shouldn't, need to take a look at that

**Comment by marquesinijatinha** [comment]
I think with the new stats on armor 2.0 this kinda became less relevant, so closing for now.
