### ISSUE TITLE
Need to disable Impeller on iOS until PaintingStyle.stroke is fixed

### ISSUE THREAD

**Issue by bill0042** [LittleLightForDestiny/littlelight#250]
LL is using PaintingStyle.stroke to render dark outlines around white text to make it more readable on light backgrounds. Flutter 3.10, by default, enables a new Impeller rendering engine (https://docs.flutter.dev/perf/impeller) on iOS which has not yet implemented PaintingStyle.stroke (https://github.com/flutter/flutter/issues/126010). We need to disable Impeller until this issue is resolved.

From (https://docs.flutter.dev/perf/impeller#ios):

To disable Impeller on iOS when deploying your app, add the following tags under the top-level <dict> tag in your app’s Info.plist file.

  `<key>FLTEnableImpeller</key>
  <false />`

**Comment by Jeanno** [comment]
Do you notice any performance issue with impeller disabled?

**Comment by bill0042** [comment]
I haven't done any comparison. We just started using Flutter 3.10 which is the first time it is enabled by default and then I started looking at this issue.

**Comment by joaopmarquesini** [comment]
I would rather find an alternative for the strokes, as we don't use them a lot.
