### ISSUE TITLE
Show complete catalyst with check

### ISSUE THREAD

**Issue by RaSSieL86** [LittleLightForDestiny/littlelight#26]
When the catalyst of a weapon is consulted and it is complete it is shown with an unmarked check.

![Screenshot_20190528-105127_Little Light](https://user-images.githubusercontent.com/9963629/58476520-3ef3a600-8151-11e9-900e-e0a74ad1ff0e.jpg)

P.S. : The catalysts consulted in collections are shown without being completed by Bungie. No improvement is possible in this regard.

**Comment by marquesinijatinha** [comment]
yeah I use the same component for every progress bar in the app, so any changes in that would need to be carefully tested to make sure it doesn't break anything else, I will check what can be done and how viable that is, but if I recall correctly, this objective is what lists the masterwork kill counter

**Comment by RaSSieL86** [comment]
I have checked all the catalysts that I have completed and they all show the same, regardless of the number of kills.

In fact in other weapons masterworks (legend) there is an extra column with the type of kills counter, but this number is not visible except when you share the image
