### ISSUE TITLE
Mods not showing up on collection item details

### ISSUE THREAD

**Issue by joaopmarquesini** [LittleLightForDestiny/littlelight#265]
![image](https://github.com/LittleLightForDestiny/littlelight/assets/305022/a8fafad0-ae89-428a-a37c-60cffd427dc0)

**Comment by bill0042** [comment]
Looks like its being caused by this code in DefinitionItemSocketControllerBloc, lines 48-52. Commenting it out makes it work.

   /// Workaround to avoid gigantic plug lists on some weapons
    final reusable = socket.reusablePlugItems;
    if (reusable != null && reusable.length > 3) {
      return [];
    }

**Comment by joaopmarquesini** [comment]
Yeah but then we need another fix for kill trackers not taking the entire screen

**Comment by bill0042** [comment]
That was only for the trackers? I'll look for another solution like maybe only returning when the first plug is a kill tracker.
