### ISSUE TITLE
iPad: in vault, frame misaligned for masterworked items

### ISSUE THREAD

**Issue by adamdowsett** [LittleLightForDestiny/littlelight#3]
On iPad, when viewing the vault, the gold frame image is misaligned to the item image. The item image is not stretched to match how non-masterworked items look.

(Example attached)

![5A8752F3-9C6C-4B05-B09C-0544954D03D8](https://user-images.githubusercontent.com/18465158/55679693-38b42b00-5953-11e9-8285-c8a127246941.png)

**Comment by marquesinijatinha** [comment]
yeah this one is a plain bug, but the app needs a major rework to look good in an ipad

**Comment by marquesinijatinha** [comment]
fixed in 1.5.8
Also made the vault show more icons instead of these gigantic ones

**Comment by adamdowsett** [comment]
Thanks, love your work!
