### ISSUE TITLE
Unable to create loadouts

### ISSUE THREAD

**Issue by SnowWolf75** [LittleLightForDestiny/littlelight#30]
I picked this app up a few days ago, because someone I was gaming with mentioned it, and i'm really impressed with it.
I've not been able to create any Loadouts, though. Seeing as it's touted as a feature, something must be wonky at my end, that I'm not seeing it. Viewing an item, I can tap the Add to Loadouts button, but nothing happens. In the Loudouts menu, there's no option to create a new one there. Is there an option I'm missing, like a SDCard for storing the data?

**Comment by SnowWolf75** [comment]
Sorry.
Moto X4, Android 9.0

**Comment by marquesinijatinha** [comment]
Hey @SnowWolf75, loadouts were a bit wonky for everyone some days ago.
I published a fix on Google Play recently, can you check if you're in the latest version ?

**Comment by SnowWolf75** [comment]
Aye, I pulled the fix a day or so afterward, and it started working now. My thanks.
