### ISSUE TITLE
Win11 Can't Reverify Credentials.

### ISSUE THREAD

**Issue by amirHizkiya** [LittleLightForDestiny/littlelight#300]
When Bungie introduced the age requirements to sign in to your account, all accounts were initially logged out. 
On Win11, because of this, I'm stuck in a loading screen. With no way of fixing it. 

<img width="930" alt="image" src="https://github.com/LittleLightForDestiny/littlelight/assets/11544085/5a2b91d1-4a74-497c-aae5-1d14fb03f192">

Side note: I uninstalling the app and installing again, it didn't work. Anything I do to fix this locally for now.

**Comment by bill0042** [comment]
The issue was fixed in v2.0.9, but I don't know if that version is available in the Microsoft app store yet. One workaround some have used is to authenticate with a different app first.

**Comment by amirHizkiya** [comment]
Can you elaborate more on different app? I have already authenticated with DIM in the browser...
