### ISSUE TITLE
iPhone and iPad heat issue

### ISSUE THREAD

**Issue by shornby** [LittleLightForDestiny/littlelight#301]
Running latest Little Light (2.0.9) on iPad m1, iPhone 12 max, and iPhone 14 pro max. All have iOS 17 beta 6. Processor is noticeably hot on all devices and battery life decreases quickly. No other apps are running. Processor cools rapidly when app closed or suspended in background. 
Thank you.

**Comment by shornby** [comment]
Btw this is **the best** app for Destiny 2!

**Comment by joaopmarquesini** [comment]
Probably related to https://github.com/hnvn/flutter_shimmer/issues/64
Fixed in v2.0.12 by disableing all "cosmetic animation" shimmers
