### ISSUE TITLE
Loadouts are gone

### ISSUE THREAD

**Issue by bernufedor** [LittleLightForDestiny/littlelight#31]
Hi, 
It seems like all my loadouts are gone and I can’t create new ones either. The whole loadouts page is just empty. 
Help would be much appreciated. 
Nevertheless thanks for this amazing app.

**Comment by bernufedor** [comment]
I have just now tested it again and everything is back up again! The loadouts page was empty for the last 2-3 days but now everything is fine again :)

**Comment by marquesinijatinha** [comment]
Hey, was you by any means the one who wrote a review stating this on iOS store ? 
The report on that person review said latest version so I was kinda worried this wasn't fixed for everyone yet.

**Comment by bernufedor** [comment]
Hey,
no, that wasn't me. I just created that one ticket. And everything works
perfectly fine now!
Kind regards,
Bernd

Am Fr., 19. Juli 2019 um 21:07 Uhr schrieb João Paulo <
notifications@github.com>:
