### ISSUE TITLE
Feature Request: Loadout Shortcuts / Widget support

### ISSUE THREAD

**Issue by sethgregory** [LittleLightForDestiny/littlelight#32]
In order to facilitate very quick loadout switching, a one-click equip shortcut would be extremely helpful.  More full-featured widget support exposing more of the app to the homescreen would be great and might follow, but just being able to create a 1x1 widget that could be set up in advance to equip `loadout foo` on `character` would be really great to have.

**Comment by marquesinijatinha** [comment]
I need to check how much of this is achievable in flutter and how would it behave when in non Android devices, but definitely a good idea

**Comment by marquesinijatinha** [comment]
It would require some platform specific code, which is something I'm willing to avoid, so closing for now.
