### ISSUE TITLE
Add option to vault everything not included in a loadout when you equip it.

### ISSUE THREAD

**Issue by Aaron-Pool** [LittleLightForDestiny/littlelight#33]
Personally, when I choose a loadout, I'd like everything that isn't a part of the loadout to go back to the vault. Just to free up inventory space for loot drops. I know this may not be everyone's preference, but adding it as a Boolean option on the loadout creation screen would be nice! 👍

**Comment by marquesinijatinha** [comment]
Hey @Aaron-Pool does the "free slots" slider cover this use case?
https://twitter.com/LittleLightD2/status/1149554542414979073

I don't think that belongs in loadout creation, but as something that you can choose when equipping/transferring said loadout
The "free slots" slider will try to move up to "X" items away from your inventory (ignoring the ones that are in the loadout)

**Comment by Aaron-Pool** [comment]
@marquesinijatinha So, yes, that's the kind of functionality I was talking about, thanks!

However, just a heads up from a UX perspective. I had _no_ idea the ghost on that screen was even clickable. The most obvious path to equipping loadouts, from a my new-user perspective, was _menu > loadouts > equip_, which doesn't have the "free slots" options. Which was why I thought the app didn't even have the functionality.

Finally, it would be nice if in the settings we could set the default for "free slots", just so I don't have to keep doing the same thing over and over, but that's just a minor gripe, and probably not a feature worth a ton of dev time.

**Comment by marquesinijatinha** [comment]
hmmm adding a setting for that makes sense!
As does adding the slider to the default loadout screen.
Making the users aware that the ghost can be tapped is an old problem that I have since I implemented it, and still couldn't come up with a solution
I was thinking about adding something like a speech balloon to it until the user click the ghost for the first time, but not sure yet.

**Comment by Aaron-Pool** [comment]
I noticed you can actually click _anywhere_ in the header. Is this intentional? If so, have you considered simply placing [this (or a simlicar) icon](https://thenounproject.com/term/drop-down/52967/) besides the `Class / Race / Attributes` column and then having that menu slide _down_ from the header instead of _up_ from the bottom?

Anyways, just my thoughts. I'm mostly a developer and I'm certainly no UX expert, but I do a little bit of this kind of thing in my day job, and it seems like that particular quick select features on loadouts is _really_ important, and I would hate for most users to miss it!
