### ISSUE TITLE
v2.0.24 for Android not saving settings

### ISSUE THREAD

**Issue by nvll** [LittleLightForDestiny/littlelight#347]
app: Android v2.0.24
os: Android version 14
device: Pixel 6a

I recently gave little light a try and have been trying to enable the following settings:
'Tap to Select'
'Enable Auto Transfers'
'Scroll Areas' 'Top Half: Sections'

They visually update in the settings menu, but when I click the arrow to the left of the heading bar, or 'back' in the Android system to get back to the app the settings are not saved. I've scrolled to the bottom and the final element I see is 'Priority Tags', and I do not see a 'save' button anywhere. When I get back to the main window no settings have been updated, and if I open settings again they are all at the unchanged defaults.

I'm unsure if I'm missing a UI element to save, or if there is a bug with how the settings save. I've checked the android application settings and there are no permissions requested to be denied. I'm happy to take some screenshots or provide further information if it helps.

**Comment by bill0042** [comment]
I am seeing this as well on iOS. There is no save button. It is supposed to save when the setting is changed. I will look into it.

**Comment by bill0042** [comment]
This appears to be a visual bug. The setting does change and take effect, but it doesn't show as being on. When it is actually on, you must tap it twice to see any change because it goes off then on again. Can you please check whether the settings are actually taking effect or not?

**Comment by bill0042** [comment]
Fixed in 2.0.25
