### ISSUE TITLE
If I leave the app on iOS and don’t force close it, the next time I open it the bottom half is cut off by a grey square

### ISSUE THREAD

**Issue by nstrasner** [LittleLightForDestiny/littlelight#35]

**Comment by marquesinijatinha** [comment]
are you on iOS 13 beta ? 
cuz I think this is an os issue

**Comment by marquesinijatinha** [comment]
closing for now as this seems to be a beta OS issue
please reopen if it happens on official releases

**Comment by nstrasner** [comment]
Sorry I just saw the notifications. Yes I am on iOS 13 beta, forgot to mention that sorry!
