### ISSUE TITLE
Request: the ability to add nicknames to weapons/armor ie. “Recluse PvP” or “Recluse PvE”

### ISSUE THREAD

**Issue by nstrasner** [LittleLightForDestiny/littlelight#36]

**Comment by RaSSieL86** [comment]
That feature is something that the developer has been wanting to implement for some time.

**Comment by marquesinijatinha** [comment]
as @RaSSieL86 said, I want to implement this along with favorites/tagging
no ETA or roadmap for that yet, but definitely something I want to!

**Comment by marquesinijatinha** [comment]
it took a year, but hey, here we are!
