### ISSUE TITLE
Request: Add mark on the character that is online

### ISSUE THREAD

**Issue by RaSSieL86** [LittleLightForDestiny/littlelight#39]
Being able to leave the character order fixed, it would now be advisable to mark the character icon on the screens where it appeared at the top.

A yellow triangle could be used in the upper left corner, similar to the one shown in the squad leader in the game itself.

**Comment by marquesinijatinha** [comment]
simple and good, may be out in the next release

**Comment by marquesinijatinha** [comment]
added in 1.6.83
