### ISSUE TITLE
Request: Treat language selection screens and settings as temporary

### ISSUE THREAD

**Issue by RaSSieL86** [LittleLightForDestiny/littlelight#40]
It would be advisable to press the back button on these screens to return to the last screen used instead of asking if you want to exit the application.

It is understood that these screens or the account selection are not pages to stay in them for a long time so treating them as temporary would give a good UX (such as the quick search screen)

**Comment by marquesinijatinha** [comment]
they affect other screens in a way they need to be rebuilt after moving from it, and changing that could introduce bugs.

**Comment by RaSSieL86** [comment]
Doing a "restart" of the app when leaving those pages would solve the problem? Like when you close the app and when opening it returns to the same screen where you left it. This way you make sure that the screen you return to with the changes applied is rebuilt. When you enter the options screen you expect to exit by pressing the back button, not changing the screen in the side menu, the same with the language change.
