### ISSUE TITLE
MMXIX seal shows 25 versus 24 triumphs for completion

### ISSUE THREAD

**Issue by kedmond** [LittleLightForDestiny/littlelight#41]
The Moments of Triumph Seal (MMXIX) shows that 25 triumphs are required for its completion when only 24 are required. I haven't noticed this issue with other seals.

![Screenshot_20190916-095743_Little Light](https://user-images.githubusercontent.com/607287/64964139-7b662180-d868-11e9-938e-e87a4779e150.jpg)

**Comment by marquesinijatinha** [comment]
that's unfortunately an issue within bungie's database, so there's nothing I can do to fix it on my side.

**Comment by kedmond** [comment]
I figured as much, but I thought it was worth reporting. Thanks!

I wonder if there was a 25th Triumph that was removed....
