### ISSUE TITLE
Light level 0 items in the Vault cause render error

### ISSUE THREAD

**Issue by mrchip2k** [LittleLightForDestiny/littlelight#42]
The item is still clickable, and is displayed correctly when equipped/in your inventory.
Before last update, the message used to be "Oof, render error"
![Screenshot_20191009-113059](https://user-images.githubusercontent.com/20379339/66469731-aec35700-ea88-11e9-82d3-596658fb19c5.jpg)
The almighty weapon of mass destruction that should have been displayed:
![Screenshot_20191009-112646](https://user-images.githubusercontent.com/20379339/66469760-ba168280-ea88-11e9-8e37-356c52d560e9.jpg)

**Comment by marquesinijatinha** [comment]
I think this is already fixed in last version, but couldn't assure as I don't have any power 0 items.
If this still happens, please reopen it.

**Comment by mrchip2k** [comment]
Can confirm it's fixed.
