### ISSUE TITLE
"Pyramidion" emblem does not show up correctly 

### ISSUE THREAD

**Issue by kedmond** [LittleLightForDestiny/littlelight#43]
I assume this is a server side problem, but I figured I'd make you aware.

Thanks, 

-Kazem 
![Screenshot_20191009-093820_Little Light](https://user-images.githubusercontent.com/607287/66486417-8f243280-ea78-11e9-80cb-b09cc683d15b.jpg)

**Comment by marquesinijatinha** [comment]
Yep it is
There's already a bungie-api issue on that one:
https://github.com/Bungie-net/api/issues/852
