### ISSUE TITLE
Rendering error after latest update

### ISSUE THREAD

**Issue by davedev** [LittleLightForDestiny/littlelight#44]
Rendering error after latest update.  Using BlueStacks.  

Short video showing error, app version and installed apps is attached.

[LL2_Bugreport_2019-10-09 18-03-09.zip](https://github.com/LittleLightForDestiny/littlelight/files/3709616/LL2_Bugreport_2019-10-09.18-03-09.zip)

**Comment by marquesinijatinha** [comment]
hmmm I'm not sure that the update caused it, looks more like corrupt app data.
try to clear app data, that should fix it.
I need to find a way to detect corrupt app data and clear it automatically.
