### ISSUE TITLE
Feature Request : Display total amount of stats on armor

### ISSUE THREAD

**Issue by cristimirt** [LittleLightForDestiny/littlelight#45]
One thing I'm sure almost all D2 players check on an armor since Shadowkeep is the total amount of stats on a piece of armor. It's an easy way to know if you got a good roll or not and it's faster than checking all individual stats.
Is it possible to show this number like it's done in the game?

**Comment by marquesinijatinha** [comment]
Yep!
I'm also planning to add some kind of highlight to items that are 60+ in listing so it's easier to know

**Comment by marquesinijatinha** [comment]
Done!
