### ISSUE TITLE
Reqest: Option for separate loadouts for all 3 characters

### ISSUE THREAD

**Issue by NullFragment** [LittleLightForDestiny/littlelight#48]
Right now when transferring extra armor it does transfer the correct armor to the correct class, but you are limited to 9 items for transfer. It'd be nice if we had the option to split up the loadouts per character, allowing us to equip and transfer a different set of weapons and armor to all characters. This is especially useful if we have multiple characters of the same class.

Two ideas for implementation:
- Add a new Triple loadout option
  - Each loadout would be assigned to a character
  - Each character would be shown on a subscreen of the loaodut
  - Each character would have their own set of weapons and armor that would be transferred
- Allow users to apply multiple loadouts at once
   - Add an option for a loadout to be assigned to a specific character
   - Allow users to create loadout groups that would apply up to one loadout per character

**Comment by marquesinijatinha** [comment]
that seems a bit overkill to me.
It would make the process more complicated for that vast majority of users
I think the current system is pretty solid as it is, maybe removing the 9 slot limitation would do the trick ? 
Also, if you want different weapons and armor for each character, why not create a new loadout?
Eg:
Garden of salvation - Titan
Garden of salvation - Hunter

Maybe adding some "tagging filters" would also make stuff easier here
like #hunter and #raid
so if you selected the tag #hunter you would only see the hunter loadouts, same with the tag #raid or #crucible.
