### ISSUE TITLE
Request: Add toggle for always removing excess items

### ISSUE THREAD

**Issue by NullFragment** [LittleLightForDestiny/littlelight#49]
A toggle for always clearing up extra items would be nice instead of having to adjust the slider to 9 every time.

**Comment by marquesinijatinha** [comment]
Have you checked the default Free Slots on settings? 
I guess that pretty much covers that one.

**Comment by marquesinijatinha** [comment]
well, I'm closing the issue as I think that feature is already covered, if I'm mistaken, please reopen it
