### ISSUE TITLE
Couldn't render this widget properly.

### ISSUE THREAD

**Issue by jiastku98** [LittleLightForDestiny/littlelight#52]
![Screenshot_2019-11-23-23-44-18-146_me markezine l](https://user-images.githubusercontent.com/32411689/69481343-69e25c80-0e4b-11ea-90ad-a5d2ed2a8a9c.jpg)

How to:
Progress--Pursuits--Choose a quest--Wait until screen turn off--Unlock the phone--Back to Pursuits

**Comment by ManlyCaveman** [comment]
I have the same issue and it happened almost identically to your steps.

**Comment by ManlyCaveman** [comment]
Looks like there was a 2.99mb update available in the play store. After updating I was able to view the menu again. Not sure if that fixed the cause though.

**Comment by Lynkar6469** [comment]
This happens to me every time I turn in a bounty. It will track just fine, but if I’m on the pursuits tap and then turn it a bounty this happens.

**Comment by marquesinijatinha** [comment]
I think I finally found the cause and fixed this on latest version.
please let me know if it starts to happen again.
