### ISSUE TITLE
Bug: Field of View pursuit not tracked

### ISSUE THREAD

**Issue by dmatijasevic** [LittleLightForDestiny/littlelight#53]
Since the last update, Field of View pursuit no longer tracks values. The numbers are fine in the game (percentages) but the app shows 0 for all three values.

**Comment by LordD2** [comment]
Same here . Progress is not being tracked on this quest.

**Comment by dmatijasevic** [comment]
It actually came back last night, just before I finished the pursuit.

**Comment by LordD2** [comment]
Did for me too, but I had to uninstall and reinstall the app.

**Comment by marquesinijatinha** [comment]
@LordD2 I fixed it in an update, you probably had an outdated version and updated when you reinstalled.
I'm closing this issue as both of you stated that this is working now.
