### ISSUE TITLE
.env file not loading

### ISSUE THREAD

**Issue by spnkr** [LittleLightForDestiny/littlelight#54]
I edited the .env.example to use real keys, and renamed it .env. When I try to auth with bungie I get an auth query string params not valid error, and the bungie URL has a clientid of "null".

Where do I put the .env file so it loads?

**Comment by marquesinijatinha** [comment]
oh sorry, I was having trouble with that and had to move the .env file to assets/_env, I will move it to the right place and update docs

**Comment by spnkr** [comment]
made a PR fixing this: https://github.com/LittleLightForDestiny/littlelight/pull/55

**Comment by marquesinijatinha** [comment]
wait a sec, I'm trying to revert to the original .env location, if that works it will be better

**Comment by marquesinijatinha** [comment]
reverted it to work as expected (using .env from project root)
