### ISSUE TITLE
Wishlists PvP vs. PvE labeling

### ISSUE THREAD

**Issue by franciscoaraposo** [LittleLightForDestiny/littlelight#56]
How can I specify whether a god roll is PvP or PvE in a wishlist file?
What part of the code is parsing the wishlist file?

**Comment by marquesinijatinha** [comment]
if you add #notes:|tags:pve,pvp,curated,trash,🤢
it will add the respective tag.
if it doesn't have those tags, it will try to parse it from the current item notes or name.
check lib/services/littlelight/dim_wishlist.parser.dart

**Comment by franciscoaraposo** [comment]
well... the parsing is bugged. for instance, when I go check my PvE godroll Pyroclastic Flow, the example below wrongly highlights Quick Launch, Impact Casing, and Ambitious Assassin as godroll perks for both PvP and PvE, even though they are PvP-only, PvE-only, and PvE-only godrolls, respectively:

this is the example wishlist code:

// Pyroclastic Flow
// Quick Launch, High-Velocity Rounds, Quickdraw, Cluster Bomb
//tags:pvp
dimwishlist:item=1289324202&perks=981914802,2822142346,706527188,1275731761
// Volatile Launch, Impact Casing, Ambitious Assassin, Cluster Bomb
//tags:pve
dimwishlist:item=1289324202&perks=1478423395,3796465595,2010801679,1275731761

It seems the parsing is bugged only when there are pvp and pve godrolls for the same weapons in the wishlist...

**Comment by marquesinijatinha** [comment]
If you're using generic notes (// or //notes:) you need to add an empty line between builds.
Eg:
```
// Pyroclastic Flow
// Quick Launch, High-Velocity Rounds, Quickdraw, Cluster Bomb
//tags:pvp
dimwishlist:item=1289324202&perks=981914802,2822142346,706527188,1275731761

// Pyroclastic Flow
// Volatile Launch, Impact Casing, Ambitious Assassin, Cluster Bomb
//tags:pve
dimwishlist:item=1289324202&perks=1478423395,3796465595,2010801679,1275731761
```

But the best way to do what you're trying to achieve is using specific tags.
Eg:
```
// Pyroclastic Flow
dimwishlist:item=1289324202&perks=981914802,2822142346,706527188,1275731761#notes=Quick Launch, High-Velocity Rounds, Quickdraw, Cluster Bomb|tags:pvp
dimwishlist:item=1289324202&perks=1478423395,3796465595,2010801679,1275731761#notes=Volatile Launch, Impact Casing, Ambitious Assassin, Cluster Bomb|tags:pve
```

**Comment by franciscoaraposo** [comment]
Thank you for clarifying this.

Is there any reference link for learning the full syntax rules for wishlists?

**Comment by marquesinijatinha** [comment]
Not yet, but I'm adopting a new format which makes more sense for little
light. Also I plan to make a GUI wishlist builder in the future.

Em qua, 26 de fev de 2020 10:12, franciscoaraposo <notifications@github.com>
escreveu:

**Comment by marquesinijatinha** [comment]
If you want to take a look, the new format looks like this:

https://raw.githubusercontent.com/LittleLightForDestiny/csv-wishlists-parser/master/output/pandapaxxy-forge.json

There's a parser for that format here:
https://github.com/LittleLightForDestiny/csv-wishlists-parser
That accepts csv like these:
https://github.com/LittleLightForDestiny/csv-wishlists-parser/blob/master/csv/pandapaxxy-forge.csv

**Comment by franciscoaraposo** [comment]
When I do (after specifying the perk codes in the same line):
#notes:Range|tags:pvp
it now correctly displays the godroll type (PvP, in this example). However,  the "|tags:pvp" also shows up in the notes :(

**Comment by marquesinijatinha** [comment]
yep, that's unfortunately a downside of the dim wishlist format.
