### ISSUE TITLE
Remove duplicated "Loadout Backgrounds" 

### ISSUE THREAD

**Issue by XTugaX** [LittleLightForDestiny/littlelight#6]
![Screenshot_20190413-084608_Little Light](https://user-images.githubusercontent.com/49588400/56080645-3295d280-5dc9-11e9-951b-377e9cdf366c.jpg)

**Comment by marquesinijatinha** [comment]
Not feasible I think. I'm trying to avoid manually managed content at all costs. Right now I grab those backgrounds from emblem collections and a lot of them have the same background.

**Comment by marquesinijatinha** [comment]
closed as possibly not feasible right now
Will reopen if I find a solution
