### ISSUE TITLE
falla al ordenar armadura 

### ISSUE THREAD

**Issue by jeobits** [LittleLightForDestiny/littlelight#61]
en ajuste en la seccion de ordenar equipo no funciona la etiqueta de personaje antes esa etiqueta la ponia en primero para que las armadura estuvieran separadas por personaje pero ahorra ya no funciona y las armaduras estan mescladas

**Comment by jeobits** [comment]
in adjustments in the order equipment section does not work, the character label before that label put in first so that the armor was separated by character but saves no longer works and the armor is mixed

**Comment by marquesinijatinha** [comment]
@jeobits can you confirm if this is fixed on latest version ?

**Comment by marquesinijatinha** [comment]
closing as I had no response and the issue seems to be fixed
