### ISSUE TITLE
Order item incomplete

### ISSUE THREAD

**Issue by carobb17** [LittleLightForDestiny/littlelight#62]
Hello, the application is great but I have noticed a small error, graphic mostly.
When searching for a weapon or armor and wanting to order it by a single item, the title of the  item appears incomplete or moved.
When adding several this does not happen

![Screenshot_20200331-050247_Little Light](https://user-images.githubusercontent.com/33585075/78014799-10fd6600-730e-11ea-9e7a-a67d20e31a64.jpg)

**Comment by marquesinijatinha** [comment]
@carobb17  can you check if this is fixed in the latest version ?

**Comment by carobb17** [comment]
Hi, yes, it's fixed now! Thank You for this great app
