### ISSUE TITLE
Good and Godroll weapon disappeared 

### ISSUE THREAD

**Issue by lilcrusader29** [LittleLightForDestiny/littlelight#65]
I have noticed that weapons have no display good or god roll in the background they are disappeared. You may take a look at that picture I uploaded it. 

![4C7B0E39-9F43-4A48-BF28-32CE4E77FE7F](https://user-images.githubusercontent.com/63473513/79018001-b7ccd800-7b40-11ea-918c-1fbb9937301b.png)

**Comment by marquesinijatinha** [comment]
try to go to settings -> wishlists
remove all wishlists then re-add Little LIght Default again
if that doesn't fix, try uninstalling/reinstalling the app
