### ISSUE TITLE
Sync tracked objectives via iCloud 

### ISSUE THREAD

**Issue by case** [LittleLightForDestiny/littlelight#67]
For the Apple platforms (iOS, Mac), I was wondering if you might consider adding sync functionality for tracked objectives, so that they appear across multiple devices? I think their iCloud offering supports this.

For example, the same tracked objectives would appear on a user’s iPhone and iPad.

**Comment by marquesinijatinha** [comment]
I may add objectives sync in the future, but by no means I intend to implement platform specific features.

**Comment by case** [comment]
Understood! It's unfortunate there isn't a way to do this via the Bungie API.

**Comment by marquesinijatinha** [comment]
Little Light already have its own API to store loadouts, I just need to do the same with objectives.

**Comment by case** [comment]
Ah ok! (Forgive my ignorance here, I'm new to Little Light but already a big fan)

Does the app sync saved loadouts somehow?

**Comment by marquesinijatinha** [comment]
yep, it does, only at startup tho, but I don't expect someone to use the app in two devices at the same time
