### ISSUE TITLE
Nature of the Beast Season 11 isn't in Collections in-app

### ISSUE THREAD

**Issue by TheTomatoLord** [LittleLightForDestiny/littlelight#70]
So I have a Nature of the Beast and wanted to see the random rolls I'll target. But found only the Season 2 Static in the app. Would love to see the Random Rolls version added soon so we can micromanage, since even with Lightgg you can't see the stat changes reflected like this app does so conveniently.

**Comment by marquesinijatinha** [comment]
the collections in the app only shows stuff that comes from Bungie's API. That being said, this is an issue of bungie API itself, unrelated to the app, and all we can do is we wait until bungie proper adds this to the list.
As a workaround until they add it, you can open the details of one instance of Nature of the Beast you own and then tap on "View in Collections" (yeah, I know, it doesn't make sense, but that's how it works unfortunately).

**Comment by marquesinijatinha** [comment]
@TheTomatoLord just as a side note: 
there's already an issue on Bungie's API repo mentioning this:
#https://github.com/Bungie-net/api/issues/1261
