### ISSUE TITLE
Pursuit search - render error

### ISSUE THREAD

**Issue by Lerie82** [LittleLightForDestiny/littlelight#71]
This error occurs when you go to the "pursuits" screen and search, if no item is found for your search, the error shows up.

![Screenshot_2020-06-28-19-43-25](https://user-images.githubusercontent.com/29735511/85968411-eb6a1200-b979-11ea-94ad-33ae3a0e12d7.png)

**Comment by lazycoder-ru** [comment]
Same, but on some quests
![image](https://user-images.githubusercontent.com/6605234/89169338-c4a98780-d586-11ea-86b2-b30ecb0b6c37.png)

**Comment by marquesinijatinha** [comment]
thanks @lazycoder-ru I've had this error on my backlog for a while but didn't know what quests triggered it.
