### ISSUE TITLE
Iron Banner weapon power caps

### ISSUE THREAD

**Issue by FallenCoronet18** [LittleLightForDestiny/littlelight#72]
I have noticed that some Iron Banner weapons in my vault are displaying a power cap of 1360, specifically Orewing's Maul, Bite of the Fox, and Talons of the Eagle. Other IB weapons like Roar of the Bear and Claws of the Wolf are showing 1060 caps.  None of the weapons in question were earned during Season of Arrivals, and all of them show a cap of 1060 in the D2 Companion app.

**Comment by marquesinijatinha** [comment]
I think this was fixed in the latest release, please reopen if it still happens
