### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by dthatch** [LittleLightForDestiny/littlelight#73]
I can’t type the name of a weapon and have it come up. When I type, nothing happens. It has to do somehow with my account or account type. I tried in 3 devices. When I switch to my sons account the search function works. I have recently cross saved to steam

**Comment by marquesinijatinha** [comment]
Hi @dthatch this is related to the new "search by loadout name" feature along with some bugged loadouts. Try to rename all of your loadouts, that should fix it until I provide a proper fix for it.

**Comment by marquesinijatinha** [comment]
I think this was fixed in the latest release, please reopen if it is still happening
