### ISSUE TITLE
Notify if Objectives are possible each week

### ISSUE THREAD

**Issue by case** [LittleLightForDestiny/littlelight#74]
I've found that Objectives tracking is one of the handiest features of Little Light -- thanks for adding this!

Some objectives are only possible to do during a given week (Tuesday-Tuesday, until next reset), e.g. Flashpoints and Heroic Adventures, or Spider WANTED bounties.

It would be really nice to get some sort of alert, if a tracked objective can be done during the current week.

**Comment by joaopmarquesini** [comment]
not possible right now
