### ISSUE TITLE
Engrams shows in lost items section

### ISSUE THREAD

**Issue by lazycoder-ru** [LittleLightForDestiny/littlelight#76]
After tapping on "Pull everything from postmaster" I see that my engrams, that even have not been losted, now in lost items section. This behavior disappears after change app screen or restarting then app.
![image](https://user-images.githubusercontent.com/6605234/90318114-de5baf00-df36-11ea-9e4a-02b5213b4011.png)

**Comment by joaopmarquesini** [comment]
@lazycoder-ru I think this is already fixed on latest build, please re-open if it still happens
