### ISSUE TITLE
More information on Duplicates screen

### ISSUE THREAD

**Issue by lazycoder-ru** [LittleLightForDestiny/littlelight#77]
It would be nice to add more information about armor on duplicates screen. At least it would be useful to see there Stat total. Now its hard to decide which copy of armor needs to be dismantled.

<img src="https://user-images.githubusercontent.com/6605234/90319144-0e5a8080-df3e-11ea-82b8-2f1fa4498433.png" width="30%" height="30%" />

**Comment by marquesinijatinha** [comment]
added all stats =D

**Comment by lazycoder-ru** [comment]
But it still hasn't total stats value)). Maybe it's just me and I remove duplicates some way wrong, but total stats it's main defining legendary armor property. Am I wrong?
