### ISSUE TITLE
Bungie profile appearance change does not affect in-app profile

### ISSUE THREAD

**Issue by lazycoder-ru** [LittleLightForDestiny/littlelight#78]
After changing my profile appearance at Bungie website, the LittleLight still shows my old profile icon and background(theme). Here some images from app and Bungie site:
App:
<img src="https://user-images.githubusercontent.com/6605234/90554345-62fc3680-e19e-11ea-9d94-a9d500e14a15.png" width="30%" height="30%"/>
Profile at Bungie:
![image](https://user-images.githubusercontent.com/6605234/90554495-a3f44b00-e19e-11ea-8361-11c16b8a6275.png)

I'm using Android 9 and play through Steam, if you need this information.

**Comment by joaopmarquesini** [comment]
I *THINK* this is already fixed, but not sure.
Please re-open if you ever find this again.
