### ISSUE TITLE
Some layout-based issues

### ISSUE THREAD

**Issue by lazycoder-ru** [LittleLightForDestiny/littlelight#79]
Here some examples when page looks little not how it should be. Maybe you can fix it.
1. Weapon type has long name and displaces power level beyond screen
<img src="https://user-images.githubusercontent.com/6605234/90556378-82e12980-e1a1-11ea-9c75-d00415bb6231.png" width="30%" heigth="30%" />

2. Weapon type overlaps ammo type and power level section
<img src="https://user-images.githubusercontent.com/6605234/90556717-0864d980-e1a2-11ea-8dd2-345b2b7878b5.png" width="30%" heigth="30%" />

3. Weapon stats doesn't fit to their blocks. Maybe it would be better if this blocks will have flexible width by the longest stat name?
<img src="https://user-images.githubusercontent.com/6605234/90557254-dbfd8d00-e1a2-11ea-98e6-0d4f2b27589c.png" width="30%" heigth="30%" />

**Comment by joaopmarquesini** [comment]
most of the layout breaking issues are fixed, but text clipping sometimes is unavoidable.
