### ISSUE TITLE
Add to settings auto refresh of triumph

### ISSUE THREAD

**Issue by RaSSieL86** [LittleLightForDestiny/littlelight#8]
Taking advantage of the fact that there is now a page of settings and it is a bit empty, add this option.

**Comment by marquesinijatinha** [comment]
Is there any advantage in disabling it?

**Comment by RaSSieL86** [comment]
Little, maybe save battery, data or load on the connection. But I think
it's not difficult to implement.

Someone may not like it to be updated only to be able to check progress
manually.
