### ISSUE TITLE
Won’t load, get this message 

### ISSUE THREAD

**Issue by basindave** [LittleLightForDestiny/littlelight#81]
![0CB4E47F-8C35-497C-9F1B-F6A96B52C4E5](https://user-images.githubusercontent.com/71190085/93002185-e48c7d80-f52c-11ea-86d9-06ff09cfe365.jpeg)

**Comment by basindave** [comment]
![F098EB8E-4DA9-43C6-AA74-D8CFACCE066F](https://user-images.githubusercontent.com/71190085/93004013-4522b700-f53b-11ea-8313-e6e5f2f9a809.png)

**Comment by basindave** [comment]
Just getting this, any ideas?

**Comment by marquesinijatinha** [comment]
try to uninstall/reinstall.
Bungie API had some instabilities last weekend and looks like you ended up with a corrupted database.

**Comment by marquesinijatinha** [comment]
closing after no response for the user.
Please re-open if it still happens.

**Comment by basindave** [comment]
Sorry for not replying.
All is good now, and thanks 
    On Monday, 5 October 2020, 14:29:36 BST, João Paulo <notifications@github.com> wrote:  
 
 


Closed #81.
