### ISSUE TITLE
Cannot lock items stored in the Vault

### ISSUE THREAD

**Issue by frieck** [LittleLightForDestiny/littlelight#82]
Hello, iOS user here!
Thanks for this  wonderfull app!
Have been trying to lock/unlock items stored in the Vault and it does not work.
Lock/Unlock items not in the Valult seems to work ok.

Thanks

**Comment by marquesinijatinha** [comment]
I'm trying to confirm, but it seems to be an issue with Bungie API.
I'm gonna look for more info and get back to you.

**Comment by frieck** [comment]
Nice!
I also use DIM (Destiny Item Manager). It is only web, don't know if they have an App but lock/unclock vaulted items seems working there.

**Comment by joaopmarquesini** [comment]
forgot about this one, seems to be fixed on last ver
