### ISSUE TITLE
Update to allow purchasing bounties

### ISSUE THREAD

**Issue by TheBrenny** [LittleLightForDestiny/littlelight#88]
With the release of the ability to purchase bounties through the API, allow users to purchase bounties through the Vendors screen (ultimately from bounty item screen).

I've already forked and started looking for a way to make this happen. No guarantees, but I'll report back with any findings I have.

Ty for the super handy app! 🙏🎂

**Comment by marquesinijatinha** [comment]
Unfortunately it's not possible yet @TheBrenny. It's only available for the official companion for now.

**Comment by TheBrenny** [comment]
I just found that out as you commented. 😅

Either way, I've updated the dart definitions, and have an acquire button ready to go - just waiting on Bungie to release an acquire API.

**Comment by marquesinijatinha** [comment]
hehe I already have some things planned when they release it for third parties.
Are you on the discord channel ?
if you're there, hit me up, I'm jaoryuken there.
