### ISSUE TITLE
[REQ] Swipe behaviour toggle

### ISSUE THREAD

**Issue by fOmey** [LittleLightForDestiny/littlelight#95]
Would love to see a "swipe behavior" toggle be added into settings.

Rather then swapping tabs between weapons/armor/inventory, a side swipe would swap characters tabs.

This would make one handed use much more intuitive I think, the tab selector located along the bottom of the screen is easily accessed already.

Perhaps pull down to refresh to be inline with all the other social media apps?

**Comment by joaopmarquesini** [comment]
A new swipe behaviour with configurable screen "areas" will be available on the next release.
Not sure about the swipe down to refresh tho.
