### ISSUE TITLE
Items reappear after moving or dismantling 

### ISSUE THREAD

**Issue by watty1964** [LittleLightForDestiny/littlelight#96]
Often I will move an item or dismantle it only for it to reappear in Little Light moments later. If my slot was full, say I had 9 helmets, and I moved one to the vault only for it to reappear then when I pick up a helmet from the postmaster the app thinks helmets are full, even though they are not, and randomly moves a helmet to the vault. This can be quite annoying. This behaviour is consistent and been happening for a few weeks. Using Little Light for Android v1. 7.57

**Comment by joaopmarquesini** [comment]
that's a known issue and kinda of an unsolvable one.
Destiny API is not always in sync with the game state and there's no way for Little Light to detect this kind of problem.
