### ISSUE TITLE
NoSuchMethod error while rendering widgets for Crucible/Gambit ranks

### ISSUE THREAD

**Issue by 1dataenthusiast** [LittleLightForDestiny/littlelight#97]
Under 'Progress' -> 'Ranks' on top of the page, the Crucible/Gambit ranks are not rendered properly but show the following error message:
`Could&#39;t render this widget properly. Please report this to @LittleLightD2 on Twitter or via GitHub issues NoSuchMethod`

The error message seems to continue but is hidden by the following rank widgets.

**Comment by joaopmarquesini** [comment]
@1dataenthusiast I think this was fixed on 1.7.60, if it still happens, please reopen this issue.
